ALTER TABLE blocks ADD COLUMN IF NOT EXISTS next_block_hash BYTEA;
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS miner VARCHAR DEFAULT NULL;
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS timestamp_received INT4 DEFAULT NULL;
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS data JSON;
